version: "3"

services:
  app:
    build: .
    image: arhangel662/heroku-dev

  caddy:
    build:
      context: .
      dockerfile: services/caddy/Dockerfile
    image: arhangel662/devops-example-caddy
